### ISSUE TITLE
Make conan-install and project-refresh events automatic

### ISSUE THREAD

**Issue by solvingj** [bincrafters/conan-vs-extension#11]
The `conan install` command should run asynchronously because it may take time to download dependencies.  Once complete, it should refresh the project, or perhaps there is some less intrusive "refresh" function in the SDK.  Probably we should try to determine/mimic what the CMake integration does.  It drops down a yellow bar with buttons to let the user refresh when they want. 

![image](https://user-images.githubusercontent.com/8557737/52488087-1ee1ac00-2b8d-11e9-97c3-752dfd98ac1e.png)

**Comment by sboulema** [comment]
The code behind the 'Install' menu item should start the 'conan install' process.
That process will be on its own thread.

In the code behind the menu item we than wait async for that process to finish:
[Process WaitForExit Async](https://stackoverflow.com/questions/470256/process-waitforexit-asynchronously)

Then the code behind can show a info bar to let the user know the process is finished:
[Infobars](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/notifications-and-progress-for-visual-studio?view=vs-2017#BKMK_Infobars)

Add an ActionItem to the infobar and subscribe an eventhandler to listen for the user clicking the refresh link.

When the refresh link is clicked we unload and reload the project using the EnvDTE
```
dte.ExecuteCommand("Project.UnloadProject");
dte.ExecuteCommand("Project.ReloadProject");
```
or using the IVsSolution4 interface:
[UnloadProject](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolution4.unloadproject?view=visualstudiosdk-2017)
[ReloadProject](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolution4.reloadproject?view=visualstudiosdk-2017)
[How To](http://www.visualstudioextensibility.com/2015/04/21/mz-tools-articles-series-howto-unloadreload-a-project-from-a-visual-studio-package/)
