### ISSUE TITLE
conanbuildinfo.props is not generated for the multi-project solution

### ISSUE THREAD

**Issue by Tadeusz-Okuljar** [bincrafters/conan-vs-extension#175]
I use Visual Studio 2017 with the conan extension. Conan extension adds a path to conanbuildinfo.props in vcxproj file, for example:

`<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
<Import Project="..\build\x86-Debug\.conan\conanbuildinfo.props" />`

 conanbuildinfo.props by default is placed in the build directory because it shouldn't be committed to the repository. When an user clones a repository and opens a solution conanbuildinfo.props should be generated. For a single-project solution it works fine.

Unfortunately it doesn't work for a multi-project solution where only one project has defined conanfile.txt. That project can't be loaded because vcxproj has a path to the conanbuildinfo.props which is not generated for the multi-project solution.

Each project in the single-project solution and multi-project solution has defined the following Output Directory:

`$(SolutionDir)build\$(PlatformShortName)-$(Configuration)\`

and Intermediate Directory:

`$(SolutionDir)build\$(PlatformShortName)-$(Configuration)\$(TargetName)\`

Is it known issue ? Do you know any workaround ?

**Comment by identify3d-joe** [comment]
I am having this same issue. What would a possible work-around be?
