### ISSUE TITLE
Support for VS 2022 (and x64)

### ISSUE THREAD

**Issue by ruilvo** [bincrafters/conan-vs-extension#194]
Hey!

Visual Studio 2022 introduced x64 builds for the first time. This broke all extensions. 
There is a [migration guide](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#extensions-written-in-a-net-language).

For extensions written in C# it's basically just an x64 rebuild. 

It would be interesting to have this working now during the beta phases and have it release-ready.

Thanks

**Comment by memsharded** [comment]
Thanks for reporting. I guess there are also other things to do in Conan first, like adding support in settings.yml for this compiler. Creating an issue for it.

**Comment by SSE4** [comment]
see also https://github.com/conan-io/conan/issues/9362
it should be a first step

**Comment by nminkov** [comment]
Now that VisualStudio 2022 was officially out for sometime, was there some progress on the extension?

**Comment by memsharded** [comment]
Nop, I am afraid at the moment this extension is on "stand-by". Until we release Conan 2.0 GA (we are in alpha now, it will take a few months, beta, etc), we will most likely not have time to resume working on this extension to update it.

**Comment by nminkov** [comment]
Thanks for the update @memsharded. It's too bad, it's an essential extension for us for transparent integration of Conan with VS. It  means we can't migrate to VS 2022. Good luck

**Comment by ruilvo** [comment]
You could try building the extension from source. I'm not sure how much of it will work, if at all, but it's certainly something you can try.

**Comment by nminkov** [comment]
Sure I will try, thanks for the suggestion

**Comment by RobLinux** [comment]
https://github.com/RobLinux/conan-vs-extension managed to upgrade and build it for 2022. but it won't work for vs2019 so just install it for 2022 :) here is the vsix : 
[Conan.VisualStudio.zip](https://github.com/conan-io/conan-vs-extension/files/7917114/Conan.VisualStudio.zip)

**Comment by playgithub** [comment]
> https://github.com/RobLinux/conan-vs-extension managed to upgrade and build it for 2022. but it won't work for vs2019 so just install it for 2022 :) here is the vsix : [Conan.VisualStudio.zip](https://github.com/conan-io/conan-vs-extension/files/7917114/Conan.VisualStudio.zip)

**UPDATE 2**

It works, but buggy, it's likely the the latest version for VS2019 also has the same problems.
After changing recipe, and install again by `conan-vs-extension`, it doesn't take effect immediately.
I haven't digged it for the reasons, I just remove the relevant libs and reinstall it, and it works.
The extension doesn't support conan profile,does it?

BTW, If install the recipe manually by command `conan` with a conan profile, and add ".props" in `Property Manager` in Visual Studio, it works well.

---

**UPDATE 1**

After installing Microsoft.VSSDK.BuildTools (version 17.0.5234 works, latest version (17.1.4054) not work),
everything builds successfully.

---

Can not build the extension in VS2022

dev/HEAD
commit id: 85138ccbe823420093aa368f1c93fdf17e26ec41 (Added: visual studio 2022 compatibility)

log
```
\path\to\conan-vs-extension\Conan.VisualStudio\Conan.VisualStudio.csproj(240,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.VSSDK.BuildTools.17.0.5234\build\Microsoft.VSSDK.BuildTools.targets.
```

**Comment by AbrilRBS** [comment]
Closing as we've just released a new vs2022, which will be the version we'll be supporting in the future, feel free to check it out in https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension&ssr=false#overview, we welcome any feedback :)

**Comment by nminkov** [comment]
Thanks!
