### ISSUE TITLE
Support for VS Linux Cross-Platform feature

### ISSUE THREAD

**Issue by jjcmru** [bincrafters/conan-vs-extension#197]
Hello, 

We use VS IDE to develop both Windows and Linux applications. For Windows applications, we have been using the Conan-vs-extension with great success.  For Linux applications, we use VS Linux cross-platform feature, which builds the Linux applications on a remote Linux machine from VS IDE in a Windows machine. However, the current version of the Conan-vs-extension does not support the VS Linux cross-platform. I wonder whether there is something in the roadmap to support this feature. 

Thanks

**Comment by memsharded** [comment]
This extension is at the moment a bit on stand-by. We are focusing efforts in Conan 2.0, and until after 2.0 is GA we will probably not have the resources to resume working on the extensions. Thanks for the suggestion!

**Comment by jjcmru** [comment]
@memsharded, Thanks for the reply! What is the target date of 2.0 GA?

**Comment by memsharded** [comment]
It depends a bit on the feedback and stabilization of alpha and beta. We are just into alpha1 and expect to do a couple of alphas more, then move to beta most likely Q1-2022.
