### ISSUE TITLE
How to use conan in VSCode

### ISSUE THREAD

**Issue by MichaelWU0726** [bincrafters/conan-vs-extension#199]
In VSCode, I installed the conan extension. But, i didn't know how to use it. Could tell me someting about it?

**Comment by uilianries** [comment]
@MichaelWU0726 How and where did you obtain this extension? Asking because there is no official extension available on VSCode and there is more than one project in Github.

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 How and where did you obtain this extension? Asking because there is no official extension available on VSCode and there is more than one project in Github.

The  conan integration for VS-Code from author `disroop` In VSCode extension shop. It seems to be official

**Comment by uilianries** [comment]
@MichaelWU0726 It's out of Conan organization, so we can't help much. Please, read https://github.com/disroop/vs-code-conan/blob/master/docs/howto.adoc and contact the author directly on his project.
