### ISSUE TITLE
Invalid setting 'Win32' is not a valid 'settings.arch' value

### ISSUE THREAD

**Issue by ForNeVeR** [bincrafters/conan-vs-extension#2]
1. Install the VSConanPackage extension (I've used the code from [this commit](https://github.com/bincrafters/conan-vs-extension/commit/1c80325da806796cceceb6400f680571f82d67ff)).
2. Create new console C++ project in Visual Studio 2017 (version 15.4.5).
3. Invoke "Tools" → "Invoke AddConanDepends" menu command.
4. It starts `conan` with the following parameters in my case:
    ```
    install . -g visual_studio_multi -s arch=Win32 -s build_type=Debug -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MDd --build missing --update
    ```

4. Conan returns the following output:
    ```
    ERROR: Invalid setting 'Win32' is not a valid 'settings.arch' value.
    Possible values are ['armv6', 'armv7', 'armv7hf', 'armv7k', 'armv7s', 'armv8', 'avr', 'mips', 'mips64', 'ppc64', 
    'ppc64le', 'sparc', 'sparcv9', 'x86', 'x86_64']
    Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
    ```

It looks like we need to translate Visual Studio platform to a Conan-supported architecture name.

**Comment by solvingj** [comment]
@ForNeVeR I'm not sure if you know , but this extension was not actually finished yet.  It is very far along, but the person who started it is taking a break for a while, and we're actively seeking contributors at this time.

**Comment by ForNeVeR** [comment]
@solvingj yes I'm aware of that. So I'm just filing the issues with existing functionality that need to be solved sooner or later.

Also, I'm aware that the nobody is currently actively working on the plugin. Maybe I could offer some help later (because I'm at the moment preoccupied with Conan plugins for another platforms).

**Comment by solvingj** [comment]
Good to know! Would love to see and discuss.

**Comment by SSE4** [comment]
right now it generates the correct command line for Win32 projects, using x86 arch. I am closing this one as no longer actual.
