### ISSUE TITLE
Add context menu entries

### ISSUE THREAD

**Issue by SSE4** [bincrafters/conan-vs-extension#20]
in addition to the global menu, it's much more convenient to have context menu for conan integration.
currently, you have to select project within solution first, then go to the global menu for conan integration.
it's much faster for UX if you can click context menu on project you just have selected.
I propose two context menus - for project and for solution (to integrate into all conan projects within solution).

**Comment by solvingj** [comment]
VS also supports the ability to add a context menu on right click of `conanfile.txt` and `conanfile.py` specifically. Not sure if that's what we want to support, but it seems like something people do.

**Comment by SSE4** [comment]
yep, sounds good as well
