### ISSUE TITLE
Doesn't work with VS 2022?

### ISSUE THREAD

**Issue by esnyderCPI** [bincrafters/conan-vs-extension#200]
Hopefully there are plans to update this tool to work with Visual Studio 2022.  It won't install from the vsix file?

**Comment by RobLinux** [comment]
https://github.com/conan-io/conan-vs-extension/issues?q=is%3Aissue+is%3Aopen+2022 ffs

**Comment by memsharded** [comment]
https://github.com/conan-io/conan-vs-extension/issues/201

**Comment by AbrilRBS** [comment]
Closing as we've just released a new vs2022, which will be the version we'll be supporting in the future, feel free to check it out in https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension&ssr=false#overview, we welcome any feedback :)
