### ISSUE TITLE
This extension development and maintenance is "on hold" until Conan 2.0

### ISSUE THREAD

**Issue by memsharded** [bincrafters/conan-vs-extension#201]
Sorry, we don't have the resources at this moment to maintain this extension.
We will resume work as soon as possible, but that means most likely after 2.0 GA.

**Comment by nminkov** [comment]
Conan 2.0 is now out. Will you continue the work on the extension 2022 support anytime soon?

**Comment by nminkov** [comment]
Bump

**Comment by memsharded** [comment]
We have already resumed work on several extensions:

- We have done some good progress in cmake-conan integration, with something that works in the develop2 branch
- Resumed work on the CLion extension, just started, very early stage

Unfortunately we couldn't prioritize everything and this extension is still on-hold. It is still planned, but we need to finalize some of the other ongoing tasks before having resources to focus on this one.

**Comment by nminkov** [comment]
Thanks for the update. 

Can you point me please to a good guide how to correctly conan v2 + Visual Studio 2022 on the command line to obtain the same result as the extension? If one exists, I don't seem to find it. 

Mean, if possible detect current build configuration (platform and all other settings), install/build all the dependencies in conan.txt, create all .props files, and integrate them in vs project.  That is, the correct use of conan toolchain for VisualStudio vs project without the extension. 

Generally, do you recommend moving to VisualStudio 2022 if using conan? Is conan v2 ready for it?

Thanks.

**Comment by MichielJazzy1** [comment]
Shameless bump, conan 2.0 has been out for a while now. The CLion plugin seems to be there.
Is there anything blocking support for VS2022/conan2.0 now?

**Comment by memsharded** [comment]
Hi @MichielJazzy1 

Thanks for the bump. No real blocker, just a matter of priorities and non infinite resources (for example, there are +500 PRs open at this moment to ConanCenter, that requires attention)
In fact, it is not fully clear if VS integration is the one to be prioritized, because VS code demand seems to become higher and higher. We still want to update this integration, but the priority wrt VS code is not decided yet.

I will bring this back to the team for discussion.

**Comment by nminkov** [comment]
@memsharded serious question. Don't you think VisualStudio is by far, the main and most popular developer environment for Windows C++ programmers? Personally I hardly imagine that affirmation to not be true, but can be wrong.

**Comment by memsharded** [comment]
From https://isocpp.org/files/papers/CppDevSurvey-2023-summary.pdf

the total number of users for VS Code is 1,082, compared with 980 for VS.

In Jetbrains survey https://www.jetbrains.com/lp/devecosystem-2022/cpp/, it is a tie at 28%

And we are seeing recently slightly more requests from Conan users wanting some VSCode integration compared with VS integration requests.

The fact that VSCode is multiplatform is playing an important role here, IMHO.

**Comment by nminkov** [comment]
Alright, it's a draw.

I believe it's crucial to acknowledge the substantial number of pre-existing Visual Studio users who are anchored to the 2019 version due to the absence of an official, straightforward, or non-hackish pathway to transition to the 2022 version. We had already chosen and invested time in Conan, primarily due to its integration with Visual Studio, albeit imperfect, it was relatively smooth.

Personally I will feel very frustrated if you let "me" on the side of the road to jump to the next shiny object. While I understand that time and resources are finite, in my opinion, continuing support for your existing user base is fundamental, especially given the sizable user base of Visual Studio. The lack of an extension for the 2022 version seems to be driving many Visual Studio users away, which I think is a significant loss on your part.

**Comment by memsharded** [comment]
You have indeed a strong argument. Even if it could be a draw, I also think that supporting already existing users should balance towards VS. Let's bump the priority of this ticket a bit, I'll take it to the team to discuss it. Thanks again for the feedback!

**Comment by nminkov** [comment]
Thanks for taking this on board and bumping up the priority. Eager to hear what the team thinks!

**Comment by nminkov** [comment]
@memsharded  any news?  
By the way, do you know of any reliable workaround or procedure to manually integrate Conan with a Visual Studio 2022 project? I haven't been able to find any, or perhaps I haven't searched thoroughly.

**Comment by memsharded** [comment]
Not yet, the ``cmake-conan`` integration has been the one needing more attention. Just took it to the team, and it seems we are good with prioritizing this over VS code, just we couldn't kick it off yet.

For VS2022, the ``MSBuildToolchain`` and ``MSBuildDeps`` would be the way to go, they should work fine with VS2022. Of course if using CMake that is a different story, but I guess you mean MSBuild. The ``conan new msbuild_lib -d name=pkg -d version=1.0`` command will create a working example.

**Comment by nminkov** [comment]
Good news about the priorities. Thanks for the tip

**Comment by AbrilRBS** [comment]
Closing as we've just released a new vs2022, which will be the version we'll be supporting in the future, feel free to check it out in https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension&ssr=false#overview, we welcome any feedback :)
