### ISSUE TITLE
Question on integration of conanbuildinfo.props and updating it's contents at pre-build time

### ISSUE THREAD

**Issue by robertfsegal** [bincrafters/conan-vs-extension#209]
Wondering about the method used to reload the conanbuildinfo.props file within the IDE after conan install gets called by the cona-vs-extension plugin.  Is there an API call or other mechanism that allows for this process?  I am trying to integrate aspects of this plugin for members of my team.  At present it would be prohibitive for folks to use the plugin outright so trying to see if I can parcel out some useful sections for folks.  I can run conan install as a pre-build event which works great but the changes to conanbuildinfo.props are always one build execution  behind i.e. if you build the project it will pickup changes to conanbuildinfo.props from the previous build execution.

Apologies I know this is isn't really an issue more a question but I wasn't sure of the best way to reach out otherwise.

**Comment by memsharded** [comment]
Hi @robertfsegal 

this IDE plugin is not maintained at the moment.
Conan created a new integration for MSBuild and VS, called ``MSBuildDeps`` and ``MSBuildToolchain``, please check: https://docs.conan.io/en/latest/reference/conanfile/tools.html, but the plugin didn't update yet, and we are at the moment fully busy with the 2.0 launch (soon). Work in this plugin will be summarized later after 2.0 is stabilized.

If I had to automate calling ``conan install`` for VS projects, I would try by injecting my own task to the projects, "hardcoding" it. It is not that the plugin does magic, but mostly call ``conan install`` for some given configurations, and then inject the results.

**Comment by robertfsegal** [comment]
Thanks @memsharded agreed on injecting Conan install commands into the project that's what I have setup through a prebuild command on the project I need it for in Visual Studio.  My issue has been that the changes made by the Conan VS generator to the .props file don't seem to get picked up using a pre-build command.  I've tried using the MSBuildDeps generator as well it doesn't seem to make a difference.

**Comment by memsharded** [comment]
> Thanks @memsharded agreed on injecting Conan install commands into the project that's what I have setup through a prebuild command on the project I need it for in Visual Studio. My issue has been that the changes made by the Conan VS generator to the .props file don't seem to get picked up using a pre-build command. I've tried using the MSBuildDeps generator as well it doesn't seem to make a difference.

Uhm, I don't know how they do it, but I learned from other users doing something similar and it worked. Maybe if it is possible to share a simplified pre-build command here, we could try and investigate a bit. I think this approach could be very convenient to many VS users, so maybe it is worth to check that (and that is something that requires way less time that maintaining the plugin, so might be doable)

**Comment by robertfsegal** [comment]
Thanks @memsharded.  Great yes if you're able to take a look at what I have for the pre-build event on my project it's much appreciated.  This is what I'm running...

`conan install $(ProjectDir) -g visual_studio -s build_type=$(Configuration) -if $(SolutionDir)\conan\Win64 -pr $(ProjectDir)\build\conan\profiles\Platforms\Win64\$(Configuration)\base`

The `conan install` command runs just fine but to capture again my problem has been the timing of when changes that are output to conanbuildinfo.props  get integrated into the build process.  That particular part of the process seems to happen after the build has completed.

**Comment by memsharded** [comment]
Sorry, I don't have enough experience with MSBuild, do you put that inside a task file or something? How do you pass that to the project so it is called? Do you have a full .props xml file with that task? In which point of your .vcxproj you import that file with that install task?

**Comment by robertfsegal** [comment]
I'm using a pre-build command essentially what gets captured inside a .vcxproj file.  Looking a bit further on this looks it has been answered several years back.  I tracked down this thread...

**launch conan install ../ from existing visual studio project msbuild chain?**
https://github.com/conan-io/conan/issues/1891

This is essentially what I wanted to do having the .props file changes available before the build starts.  Seems Visual Studio doesn't allow for this.
