### ISSUE TITLE
Subscribe to conanfile.txt / conanfile.py changes

### ISSUE THREAD

**Issue by SSE4** [bincrafters/conan-vs-extension#21]
if automatic integration is enabled, plug-in must handle:

- user adds new/existing `conanfile.txt` or `conanfile.py` into project
- user modifies (saves) existing `conanfile.txt` or `conanfile.py` within project

I'd prefer only watch for conanfiles which are items within solution.
if conanfile exists somewhere in project directory, but not added, we're currently not going to watch for file system events.

**Comment by solvingj** [comment]
I think it's ok to say that if you want it to be "automatic", you have to make it part of the solution.
