### ISSUE TITLE
Does Conan support out of the box integration of generated props file into visual studio project?

### ISSUE THREAD

**Issue by sandybhat16** [bincrafters/conan-vs-extension#210]
### What is your question?

I am installing a conan package with generator - MSBuildDeps. This generates a bunch of props file. I want to automate the process of installing the conan package by having the conan install script as a pre-build event in the visual studio. Currently I am manually updating the visual studio project file by adding the entry to the props file. Taking a step ahead, I also want to automate the process of adding the props file into the visual studio project file. Does Conan provide an out of the box solution for this?

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

thanks for your question

>  I want to automate the process of installing the conan package by having the conan install script as a pre-build event in the visual studio. Currently I am manually updating the visual studio project file by adding the entry to the props file. Taking a step ahead, I also want to automate the process of adding the props file into the visual studio project file. Does Conan provide an out of the box solution for this?

Not at this moment. We have the https://github.com/conan-io/conan-vs-extension VS extension that was aim at this, but at the moment it is abandoned. We have plans to resume working on this. That doesn't meant that the approach will be a VS extension, but it actually might be a msbuild task that can be plugged in into the projects without really needing a VS IDE extension.

In any case, the place where this will be discuss will be https://github.com/conan-io/conan-vs-extension, should I transfer this ticket there?

**Comment by sandybhat16** [comment]
@memsharded Thanks for your response. Sure you can move it.
 Sounds good. Hoping this will be available soon :)

**Comment by AbrilRBS** [comment]
Closing as we've just released a new vs2022, which will be the version we'll be supporting in the future, feel free to check it out in https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension&ssr=false#overview, we welcome any feedback :)
