### ISSUE TITLE
Missing "Add requirement" button

### ISSUE THREAD

**Issue by Todiq** [bincrafters/conan-vs-extension#225]
Hello!

I am using conan 2.2.0 and VS 17.8.8 LTSC. I just installed the extension v2.0.1, but it looks like there is an issue with the GUI, making it impossible to install any conan package. My conan executable is accessible through a virtualenv. I tried starting VS from both its executable in the Windows' start menu and from a terminal which had the venv activated, but both cases led to the same issue.

We can see that the "Add requirement" button is not present. Could you please have a look? Thank you!
<img width="870" alt="image" src="https://github.com/conan-io/conan-vs-extension/assets/103094299/864b1e55-aa40-43dd-aeb0-e35dee069220">

**Comment by czoido** [comment]
Hi @Todiq, the `Add requirement` button should appear right after clicking `OK` in the window on the right and after you select one of the libraries of the list on the left. Could you please try?

**Comment by Todiq** [comment]
Hello @czoido,

Thanks for the quick response. Unfortunately, it still does not do anything

**Comment by czoido** [comment]
@Todiq, Could you please first click he refresh button (🔄) on the list of the left and after that click on any library of the list and send an screenshot of that?

**Comment by Todiq** [comment]
@czoido,

Clicking the refresh button gave me the confirmation window (libraries data file updated), but it still does not display anything after selecting any package

<img width="367" alt="image" src="https://github.com/conan-io/conan-vs-extension/assets/103094299/e251baf5-2b2d-457e-b8ad-33b867588d21">

**Comment by czoido** [comment]
Hi @Todiq,
I tried to reproduce with no luck, I'm using a newer version: 17.9.3, I don't know if maybe that has something to do.
Have you tried to restart Visual Studio in case for any reason the plugin initialization when starting VS did something wrong?

**Comment by danimtb** [comment]
I have tried from my side with the VS 2022 version I have installed (17.8.6) and it worked fine for me.
I installed the plugin fresh from the marketplace and the "Add requirement" button appears when I click on one library.

Not sure if this could be an issue of this VS specific version or just an initialization issue of the plugin. Please try restarting visual studio and selecting other conan client path or use the one from the system. Also, although it might be unrelated, try with a different project as well.

**Comment by Todiq** [comment]
@danimtb,

I think it might come from the conan client. I fully reinstalled VS (Pro edition), now in version 17.9.5, to get the same error. I still have to try installing conan system-wide to check if it fixes the issue

**Comment by Todiq** [comment]
@danimtb 

I tried using conan system wide, switching VS to english and installing the extension through the release page but still cannot get it to work. May it be caused by my `CONAN_HOME`? It is set to a specific location. Unless it is because I use the Pro edition of VS, but that would not make much sense

**Comment by czoido** [comment]
Hi @Todiq,
I think we finally found the problem. The plugin is only compatible with Visual Studio projects that use _msbuild_, so it's trying to detect some properties from the _vcproj_ and if there's none it may fail. Is it possible that you are trying to use the plugin from a project that's not C++ or maybe it's a C++ CMake project?
Could you please try to use the plugin from a new C++ project created from the Visual Studio template like this?

<img width="967" alt="image" src="https://github.com/conan-io/conan-vs-extension/assets/5045666/0ac7b773-9361-4955-9e32-6d00fdcb2be5">

I think that could be the case, and we have to make some kind of detection of the project the plugin is running in to provide users a warning message about this.
Please try and ping us back.

**Comment by Todiq** [comment]
I tried without selecting a project and with my c++ cmake project, but that led to the display issue. It does indeed work properly with the console app template

**Comment by czoido** [comment]
@Todiq, thanks a lot for reporting this, [we have opened a PR](https://github.com/conan-io/conan-vs-extension/pull/226) to a warning for cases where the extension is not meant to work to help users.

**Comment by Mr-Luckyowl** [comment]
In July, 30 2026, I have still this problem. I cannot click Add Requirements in order to add fmt. I am using MSVC 2022 with newest patch level (17.14.37) and extension is installed properly. Any solutions?

**Comment by memsharded** [comment]
Hi @Mr-Luckyowl 

Thanks for the feedback.
This issue was closed as solved. Could you confirm which project type did you select?

**Comment by Mr-Luckyowl** [comment]
**I am so sorry!** I have just controlled and found that was a fault mixed files from MSVC-2026 without MSBuild.
And now **I deleted these bad files** and **it works**. By and thx 4 this conan2.

P.S: Is Conan2 to handle *.midl, *.vcxproj or other stuff? Maybe you could send me link where to find it, because google goes crazy and show me not right sights. Thx.,

**Comment by memsharded** [comment]
> I am so sorry! I have just controlled and found that was a fault mixed files from MSVC-2026 without MSBuild.
And now I deleted these bad files and it works. By and thx 4 this conan2.

No worries! Happy that you found the issue and it is working now.

> P.S: Is Conan2 to handle *.midl, *.vcxproj or other stuff? Maybe you could send me link where to find it, because google goes crazy and show me not right sights. Thx.,

If you mean the tools for Conan reicpes specific to integrate with MSBuild projects, those are the tools in https://docs.conan.io/2/reference/tools/microsoft
