### ISSUE TITLE
Poor contrast in tool window when using VS Dark theme

### ISSUE THREAD

**Issue by Seally** [bincrafters/conan-vs-extension#229]
Some tool window items are barely visible when using the Visual Studio Dark theme, as seen in this screenshot:

![image](https://github.com/conan-io/conan-vs-extension/assets/507710/4fe26f4f-be52-4df4-b864-8e359928b0a4)

Additionally, the installed libraries list probably should not use a white background. I think the plugin should try to follow the theme's choice of colours whenever appropriate.

Plugin version: 2.0.2
Visual Studio version: 17.9.6

**Comment by czoido** [comment]
Hi @Seally,
Thanks a lot for reporting. Adding this to be improved in 2.0.3 version.

**Comment by memsharded** [comment]
I have hit this myself today.

**Comment by czoido** [comment]
Hi @Seally, we have just released 2.0.3 version that adapts better to the themes, thanks a lot for reporting!

**Comment by czoido** [comment]
@Seally we have detected some problems with 2.0.3 and had to revert, please do not update yet, we will fix this in 2.0.5

**Comment by czoido** [comment]
@Seally this has been finally fixed in 2.0.5, now the plugin adapts to both dark and light theme
