### ISSUE TITLE
[Bug] The linkage type generated during the dependencies compilation mismatches the project one

### ISSUE THREAD

**Issue by Jeanmilost** [bincrafters/conan-vs-extension#233]
In one of my Visual Studio project, I'm compiling a static DLL, as you can see on the below project option:

![image](https://github.com/conan-io/conan-vs-extension/assets/22838173/514ab804-f3a8-4944-b6fc-912d13d71fd4)

However, when Conan compile my dependencies, it generates this configuration file:
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic    <== !!! This is not matching my project options !!!

compiler.runtime_type=Debug
compiler.version=193
os=Windows
```

As the Conan config file mismatches the one in my project option, I get this error during the linking time:

> Error LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in MyRPCClient.obj MyShellExt C:\Projets\branches\vs2022_dev\MyShellExt\libboost_thread.lib(thread.obj)	1

On the other hand, if I manually correct my config file as below:
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=static

compiler.runtime_type=Debug
compiler.version=193
os=Windows
```

the project compiles and links as expected.

Can you please fix that?

**Comment by memsharded** [comment]
Hi @Jeanmilost 

Thanks for reporting.

I am submitting a potential fix in https://github.com/conan-io/conan-vs-extension/pull/235.  It is the first time I contribute to the extension, I don't know enough about it, but looks doable.

**Comment by Jeanmilost** [comment]
@memsharded Thank you very much :-)

**Comment by czoido** [comment]
Hi @Jeanmilost we have just released 2.0.3 version of the plugin that should fix this, thanks a lot for reporting

**Comment by czoido** [comment]
@Jeanmilost  we have detected some problems with 2.0.3 and had to revert, please do not update yet, we will fix this in 2.0.5

**Comment by Jeanmilost** [comment]
@czoido Ok, thank you for the notification.

**Comment by czoido** [comment]
@Jeanmilost finally these changes come in 2.0.5 that we have just released
