### ISSUE TITLE
Restore "Conan Package Management" menu

### ISSUE THREAD

**Issue by SSE4** [bincrafters/conan-vs-extension#24]
there is "Conan Package Management" menu, but it currently just displays and empty Windows.
I think it should do something useful (e.g. show HTML of conan graph, for instance).

**Comment by SSE4** [comment]
@solvingj do you remember what was planned for this?

**Comment by solvingj** [comment]
I'm not sure, I think this was intended to be the top level menu. Currently, we have a top level called "Conan".  

If it's not too much trouble, I would prefer it be under: 
Tools -> Conan Package Manager
Just like the Nuget Package Manager toolbar is today.
