### ISSUE TITLE
[Bug] Extension not detecting changes in conanfile.py

### ISSUE THREAD

**Issue by atanadan-flutterint** [bincrafters/conan-vs-extension#242]
This is what I get when I try to build after making changes to conanfile.py:
```
1>Checking changes in conanfile.py
1>No changes detected, skipping conan install...
```
It doesn't matter what I change in the file, it just gets ignored

**Comment by czoido** [comment]
Hi @atanadan-flutterint,

Thanks a lot for reporting, I could reproduce and in fact there's an small bug in the bat script that checks the files for changes, we will fix this in the next release soon.
