### ISSUE TITLE
[Question] Cannot install the latest libjpeg version if the libpng version is also installed

### ISSUE THREAD

**Issue by Jeanmilost** [bincrafters/conan-vs-extension#246]
I don't know if it's the right location to post this issue. If not, please tell me where to post it.

In a project I need to install Libjpeg alongside with libpng. With some other projects I could successfully install the latest libjpeg version, which is today the 9f version. However, as soon as I add the libpng in my install list, I get the below error:

> 1>EXEC : error : Version conflict: Conflict between libjpeg/9e and libjpeg/9f in the graph.

Would it be possible to allow to install libpng alongside with the latest libjpeg version?

**Comment by memsharded** [comment]
Hi @Jeanmilost 

This is not really related to this plugin, it would be more a general Conan ``conan`` repo question.

This is a version conflict, please check: https://docs.conan.io/2/tutorial/versioning/conflicts.html

It would be necessary to know which exact versions you are depending on. In general ConanCenter tries that the latest versions are jointly compatible.

**Comment by danimtb** [comment]
Closing this issue as unrelated. Please check the docs as commented above or open an issue in the conan client repository. Thanks!
