### ISSUE TITLE
Projects using conan extensions cannot be executed after moving the project

### ISSUE THREAD

**Issue by zhangshiyu12345** [bincrafters/conan-vs-extension#250]
After using this extension, I successfully generated an. exe file. However, if I move this. exe file to a new environment without the corresponding conan package, it will fail to execute. How can I solve this problem

**Comment by memsharded** [comment]
If it has shared dependencies, you will need to gather them, maybe using a ``--deployer``, like the runtime one. Or you might try to link it statically, it depends on how you are building the executable.
