### ISSUE TITLE
Different libraries contain the same conan package, how to introduce it

### ISSUE THREAD

**Issue by zhangshiyu12345** [bincrafters/conan-vs-extension#252]
How do I have two libraries that contain Conan packages with the same name, now how do I introduce packages from one library in conandata.yml file to distinguish them?

**Comment by czoido** [comment]
Hi @zhangshiyu12345,
Thanks for the question. Could you please elaborate a bit more on your use case? Libraries do not contain conan packages, do you mean the opposite? Do you have packages with the same name that contain different libraries?

**Comment by zhangshiyu12345** [comment]
I now have two libraries, demo1 and demo2, both of which have a conan package called gang-test, and now I'm going to use the package from demo1 ，now how to distinguish between them in the conandata.yml

**Comment by zhangshiyu12345** [comment]
Now I need to add both of the same name packages in demo1 and demo2 to the conandata.yml, how can this be fixed

**Comment by czoido** [comment]
Hi @zhangshiyu12345 ,

- If `demo1` and `demo2` are completely different libraries and unrelated you should package them in Conan packages with different names. 
- If those two libraries are the product of the same build process, you just have to add `gang-test` to the `conandata.yml` and they both should be available. You could also differentiate those libraries as components, you can check the docs here: https://docs.conan.io/2/examples/conanfile/package_info/components.html

Hope this helps.

**Comment by czoido** [comment]
Hi @zhangshiyu12345,
Is this still an issue o may we close the ticket?
Thanks a lot!

**Comment by czoido** [comment]
Closing the ticket, please feel free to reopen or open a new one if you have any more questions.
