### ISSUE TITLE
[BUG] Projects in soulution folders are not detected properly

### ISSUE THREAD

**Issue by Maju-Ketchup** [bincrafters/conan-vs-extension#254]
**Version 2.0.7**

**What happens:**
When a project is in a Solution subfolder of a solution no Conan Package can be added, because the project is not recognized as msvc project. So no library can be added via the extention.

**What should happen:**
Projects in a subfolder of a solution should be detected as others.

**Current Workaround:**
Move the project direct under the solution, add the libraries, then move it back.

**Comment by czoido** [comment]
Hi @Maju-Ketchup,

Thank you so much for reporting.

I confirmed that this issue is happening as you describe. I have added this to the milestone for the next release.

**Comment by czoido** [comment]
Hi @Maju-Ketchup,

We have just released 2.0.8 version of the extension that should solve this issue.

Thanks a lot for reporting.
