### ISSUE TITLE
Installation of Extension fails

### ISSUE THREAD

**Issue by Blitzo1** [bincrafters/conan-vs-extension#260]
When I install the current extension in Visual Studio 2022 and start it, I get "The 'ConanToolWindowPackage' did not load correctly". The ActivityLog.xml refered to in the message does not give additional info... can anyone give me a clue here?

**Comment by Shtille** [comment]
Same for me. In ActivityLog.xml we get error:
"SetSite failed for package [ConanToolWindowPackage](null)"

**Comment by czoido** [comment]
Hi @Blitzo1, @Shtille 
Thanks a lot for reporting. Did this happen after updating to 2.0.8 version? Or is this after an install from scratch?
Does it happen when you load the project?
Could you please give us some more details about the Visual Studio and plugin versions?

**Comment by Blitzo1** [comment]
Hi @czoido,
install from scratch, version 2.0.8; Visual Studio Community 2022 17.12.3. The error is displayed when I load the solution (I guess actually when I load the project that uses conan...) and everytime I want to show the conan-dialog (View -> Windows -> conan...).
Thanks for looking into this!

**Comment by Shtille** [comment]
Hi @czoido 
For me too, install from scratch, 2.0.8. Visual Studio 2022 17.12.3. Error is displayed when I open Visual Studio (I didn't even load the CMake based project).

**Comment by czoido** [comment]
Hi @Shtille, @Blitzo1,
Sorry fort this and thanks a lot for reporting, we have just release 2.0.9 that should fix this problem. It should be available in a couple of minutes.

**Comment by Blitzo1** [comment]
Hi czoido,
works over here! Thanks for the super quick fix!

**Comment by Shtille** [comment]
Yes, 2.0.9 works fine!
