### ISSUE TITLE
[Question] Version sorting

### ISSUE THREAD

**Issue by shrddr** [bincrafters/conan-vs-extension#262]
For most packages, the items in version dropdown are sorted from latest to oldest. Is there a specific reason why `pcapplusplus` is different? This leads to outdated version being selected by default.
![image](https://github.com/user-attachments/assets/af5bd9eb-f37b-4df4-9855-a15a0ef69d9c)

**Comment by AbrilRBS** [comment]
Hi @shrddr thanks a lot for your report.

The version ordering currently follows that of the declaration order in Conan Center Index, not the semver version. I've proposed https://github.com/conan-io/conan-clion-plugin/pull/218 to fix this issue and make the versions follow the expected conventions :)

**Comment by czoido** [comment]
Hi @shrddr,
Thanks a lot for reporting, the issue should be fixed now, all you have to do is to click on the update packages button for the extension:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/750ab979-0d69-4eb5-9a51-a3f3dba78df4" />
and next time you select the library the correct version should appear as default.
