### ISSUE TITLE
Info from VS cmake integration

### ISSUE THREAD

**Issue by solvingj** [bincrafters/conan-vs-extension#3]
Of note, I just found this in the `.vcxproj` that is generated when using Visual Studio's CMake project integration. I don't know if it's similar to what we are doing or not. 

I think when it comes to generating and injecting content into the MSVC project files, it's helpful to look at examples that others are using (especially MS). So, this example might simply give us good instruction on what text to inject as a custom command. 

```
  <ItemGroup>
    <CustomBuild Include="C:\Users\jerry\git-c\solvingj-learning-c-02\CMakeLists.txt">
      <Message Condition="'$(Configuration)|$(Platform)'=='Release|x64'">Building Custom Rule C:/Users/jerry/git-c/solvingj-learning-c-02/CMakeLists.txt</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='Release|x64'">setlocal
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -HC:/Users/jerry/git-c/solvingj-learning-c-02 -BC:/Users/jerry/CMakeBuild/a8a3ec8f-095d-283f-8a34-b928d49d0346/build/x64-Release --check-stamp-file C:/Users/jerry/CMakeBuild/a8a3ec8f-095d-283f-8a34-b928d49d0346/build/x64-Release/CMakeFiles/generate.stamp
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal &amp; call :cmErrorLevel %errorlevel% &amp; goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd</Command>
```

**Comment by SSE4** [comment]
I think we're trying to not pollute projects as much as possible, keeping project changes limited to just props injection. all other logic happens in the plug-in itself.
