### ISSUE TITLE
Change --install-dir to use $(INT_DIR) or $(OUT_DIR) instead of /conan

### ISSUE THREAD

**Issue by solvingj** [bincrafters/conan-vs-extension#8]
The `conan install` command will eventually occur automatically upon switching configurations and architectures in VS, and will generate separate and unique versions of `conanbuildinfo.props` for each unique configuration.  Thus, these should be generated under the unique directory used for other "auto-generated" files from visual studio for each build, so that they do not overwrite each other.

One concern we'll have to think about is the effect of visual studio's "clean" functionality, and whether or not it will wipe out this file.  Do we want it to?  It seems like the effect on intellisense would be detrimental overall, so probably not. 

If that's the case, I guess I would suggest something like `.conan/$(OUT_DIR)` where we just mimic the unique directory structure used for by VS for builds, but in our own subdirectory so it doesn't get cleaned. 

Lets try the `$(OUT_DIR)` for now and if it causes problems, we'll consider the alternative.

**Comment by SSE4** [comment]
I don't think it plays nicely with `visual_studio_multi` generator - we need single location for `conanbuildinfo_multi.props` and its siblings. since each configuration may have its own `OUT_DIR` and `INT_DIR`, this doesn't fit, obviously.
but I support changing `conan` -> `.conan`.

**Comment by solvingj** [comment]
This is part of the reason for not using multi generator.

**Comment by SSE4** [comment]
`visual_studio` generator now installs to the `$(OUT_DIR)/.conan`
