### ISSUE TITLE
Add parsing of JSON configuration file: conan-vs-settings.json

### ISSUE THREAD

**Issue by solvingj** [bincrafters/conan-vs-extension#9]
Now that the plugin is semi-functional, the next "feature" will be the parsing of a JSON config file. 

Lets start by just looking for this filename in the root of the project: `conan-vs-settings.json`

Start with a schema version number of `0.1.0` and an object that lets users override the first behavior which is the `conan install` step. 

In an abstract sense,  `conan_install` will be the name of an action that will be invoked from the `conan -> install` menu, and also automatically upon project load.  This could be modeled a few ways in the JSON schema.  I'm not sure which will work out best. Here's simple example:

`"conan_install" : { "args" : "<user can fully declare args to override hard-coded/dynamic args>"}`

or, for a more robust/future-thinking approach: 

```
  "conan_commands" : {
    "install" : { 
      "args" : "<user can fully declare args to override hard-coded/dynamic args>"}`
    }
  }
```

**Comment by sboulema** [comment]
PR submitted!

Ended with this this JSON layout:
```
{
    "Version": "0.1.0",
    "ConanCommands": [
        {
            "Name": "install",
            "Args": "install -test"
        }
    ]
}
```

**Comment by SSE4** [comment]
this has been implemented by @sboulema
